### ISSUE TITLE
Readme images are returning 403 forbidden

### ISSUE THREAD

**Issue by johanbrandhorst** [VividCortex/ewma#11]

**Comment by Preetam** [comment]
@xaprb, can you upload the images here so I can hotlink in the README?

![image](https://user-images.githubusercontent.com/379404/28241484-74d95f7e-6963-11e7-85e8-1ca3e4e735c7.png)

**Comment by xaprb** [comment]
<img width="821" alt="series" src="https://user-images.githubusercontent.com/279875/28242350-463289a2-6977-11e7-88ca-fd778ccef1f0.png">
<img width="819" alt="step-n" src="https://user-images.githubusercontent.com/279875/28242352-464c58f0-6977-11e7-8cd0-e01e4efaac7f.png">
<img width="822" alt="step-2" src="https://user-images.githubusercontent.com/279875/28242351-464abefa-6977-11e7-95d0-43900f29bef2.png">
<img width="818" alt="step-1" src="https://user-images.githubusercontent.com/279875/28242353-464c96bc-6977-11e7-9981-dc4e0789c7ba.png">
