### ISSUE TITLE
Test fail on arches ppc64le and s390x

### ISSUE THREAD

**Issue by eclipseo** [VividCortex/ewma#14]
Hello,

I am in the process of packaging ewma for Fedora but I encountered problems running the tests. On both ppc64le and s390x arches, the following test fails:

```
+ export GOPATH=/builddir/build/BUILDROOT/golang-github-VividCortex-ewma-0-0.1.git4cc8cc5.fc27.ppc64le//usr/share/gocode:/usr/share/gocode
+ GOPATH=/builddir/build/BUILDROOT/golang-github-VividCortex-ewma-0-0.1.git4cc8cc5.fc27.ppc64le//usr/share/gocode:/usr/share/gocode
+ go test -compiler gc -ldflags '' github.com/VividCortex/ewma
--- FAIL: TestSimpleEWMA (0.00s)
	ewma_test.go:26: e.Value() is 4734.500946466117, wanted 4734.500946466118
--- FAIL: TestVariableEWMA (0.00s)
	ewma_test.go:40: e.Value() is 4734.500946466117, wanted 4734.500946466118
FAIL
FAIL	github.com/VividCortex/ewma	0.018s
```

Could you identify why there is a discrepancy in the value given versus the value expected, only on these two arches while others arches test are fine?

**Comment by Preetam** [comment]
Not sure... maybe there's a subtle difference with floating point arithmetic? They're only off by 0.000000000001, so maybe we should change the tests so they check that the value is within some range.

**Comment by Preetam** [comment]
Tagged v1.1.1. https://github.com/VividCortex/ewma/releases/tag/v1.1.1
