### ISSUE TITLE
Link to picture of cat 404's

### ISSUE THREAD

**Issue by diogomonica** [VividCortex/ewma#5]
I was really looking forward to seeing the picture of the moving average cat.

![screenshot 2015-03-15 10 24 22](https://cloud.githubusercontent.com/assets/55332/6657080/772f2436-cafd-11e4-917a-89a070fd733c.png)

**Comment by Preetam** [comment]
Sorry about that. I tried my best to find that picture but failed. I removed that image from the README via https://github.com/VividCortex/ewma/commit/c34099b489e4ac33ca8d8c5f9d29d6eeaf69f2ed but forgot to close this issue.
